### ISSUE TITLE
안녕하세요 소스코드를 참고해서 CNN을 실습해보려 하는데요.

### ISSUE THREAD

**Issue by pervin0527** [thomaspark-pkj/tf-image-classification#1]
소스코드 작성하셨을때의 버전과 현재의 tensorflow 버전 차이 때문인지
train을 실행시켰을때 결과가 계속해서 nan이 발생하는데요. 어느 부분이 문제인지 저로써는 잘 모르겠어서 이렇게 질문을 남겼습니다.

**Comment by digitalbrain79** [comment]
@pervin0527 Tensorflow 처음 공부할때 작성했던 코드라 업데이트는 안하고 있습니다. 동작 안하는 이유는 버전 차이 때문이 맞는것 같습니다. 최근에는 좋은 예제 소스들이 많으니 다른 소스를 참조하시는 것을 추천합니다.
